api-version: '1.13'
author: Epicnicity322
depend: [ EpicPluginLib ]
description: Plays sounds at player events.
main: com.epicnicity322.playmoresounds.bukkit.PlayMoreSounds
name: PlayMoreSounds
version: '${project.version}'
website: https://www.spigotmc.org/resources/37429/

commands:
  playmoresounds:
    aliases:
      - pms
      - sounds
      - moresounds
    description: 'PlayMoreSounds''s main command.'

permissions:
  playmoresounds.player:
    description: Player recommended permissions.
    default: true
    children:
      playmoresounds.disc.use: true
      playmoresounds.help: true
      playmoresounds.listen.teleport: true
      playmoresounds.reproduce.teleport: true
      playmoresounds.toggle: true
      playmoresounds.toggle.check: true